version: 2.1

# -------------------------
# EXECUTORS
# -------------------------
# Re:VIEWのバージョンアップ時はここが変わる or 増える
# ここ以外にCircleCIで考慮しなくていいようにする
executors:
  # Executorではジョブ間で再利用するDockerイメージを定義する
  # https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
  vvakame-executor:
    working_directory: ~/tmp
    docker:
      - image: vvakame/review:4.1

# -------------------------
# COMMANDS
# -------------------------
commands:
  # ジョブ内で実行するステップシーケンスをマップとして定義する。複数のジョブ間でコマンド定義を再利用できる
  # https://circleci.com/docs/ja/2.0/configuration-reference/#commandsversion21-%E3%81%8C%E5%BF%85%E9%A0%88
  restore_cache_checkout:
    steps:
      - restore_cache:
          key: review-repo-{{ .Environment.CIRCLE_SHA1 }}
  save_cache_checkout:
    # save_cache_checkoutコマンドは再利用できるようにしていますが実質的にはsetupのタイミングでしか利用しません
    steps:
      - save_cache:
          key: review-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/tmp

  restore_npm_deps:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-cache-{{ checksum "package-lock.json" }}
  save_npm_deps:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

jobs:
  setup:
    executor: vvakame-executor
    steps:
      - checkout
      - save_cache_checkout
      - restore_npm_deps
      - run:
          name: Initial Setup
          command: npm install
      - save_npm_deps
  test:
    executor: vvakame-executor
    steps:
      - restore_cache_checkout
      - restore_npm_deps
      - run:
          name: Test
          command: npm test
  build:
    executor: vvakame-executor
    steps:
      - restore_cache_checkout
      - restore_npm_deps
      - run:
          name: Build PDF
          command: npm run pdf
      - run:
          name: Preparing artifacts
          command: |
            mkdir -p /tmp/artifacts
            cp ./articles/*.pdf /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: /
workflows:
  version: 2
  test-and-build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup

